version: '3.4'
services:
  test_stanafra:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.local
      args:
        DB_CONNECTION: "postgresql://postgres:mysecretpassword@db:5432/postgres"
        MODE: "TEST"
    entrypoint: >
      sh -c "sleep 5 && make test"
    volumes:
      - ../:/app/
    environment:
      - PYTHONPATH=/app/backend/stanafra/stanafra
    links:
      - "db:db"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  stanafra:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.local
      args:
        DB_CONNECTION: "postgresql://postgres:mysecretpassword@db:5432/postgres"
        MODE: "TEST"
    entrypoint: >
      sh -c "sleep 5 && python ./backend/stanafra/stanafra/main.py"
    volumes:
      - ../:/app/
    environment:
      - PYTHONPATH=/app/backend/stanafra/stanafra
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/v1/version"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    links:
      - "db:db"
    depends_on:
      - db
  frontend:
      build:
        context: ../
        dockerfile: ./docker/frontend/Dockerfile
      volumes:
        - ../:/fe
      ports:
        - "80:80"
  